apiVersion: v1
kind: Namespace
metadata:
  name: kdm-presto
---
kind: Job
apiVersion: batch/v1
metadata:
  name: coordinator
  namespace: kdm-presto
  labels:
    presto: coordinator
spec:
  activeDeadlineSeconds: 60
  # replicas: 1
  # parallelism: 2
  template:
    metadata:
      labels:
        presto: coordinator
    spec:
      containers:
      - env:
        - name: HTTP_SERVER_PORT
          value: "8080"
        - name: PRESTO_JVM_HEAP_SIZE
          value: "8"
        - name: PRESTO_MAX_MEMORY
          value: "10"
        - name: PRESTO_MAX_MEMORY_PER_NODE
          value: "1"
        image: johandry/presto
        livenessProbe:
          exec:
            command:
            - /etc/init.d/presto status | grep -q 'Running as'
          failureThreshold: 1
          periodSeconds: 300
          timeoutSeconds: 10
        name: presto-coordinator
        ports:
        - containerPort: 8080
      restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: presto
  namespace: kdm-presto
spec:
  selector:
    presto: coordinator
  type: NodePort
  ports: 
    - port: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    presto: worker
  name: worker
  namespace: kdm-presto
spec:
  activeDeadlineSeconds: 60
  # replicas: 1
  parallelism: 2
  template:
    metadata:
      labels:
        presto: worker
    spec:
      containers:
      - env:
        - name: HTTP_SERVER_PORT
          value: "8080"
        - name: PRESTO_JVM_HEAP_SIZE
          value: "8"
        - name: PRESTO_MAX_MEMORY
          value: "10"
        - name: PRESTO_MAX_MEMORY_PER_NODE
          value: "1"
        - name : COORDINATOR
          value: "presto"
        image: johandry/presto
        livenessProbe:
          exec:
            command:
            - /etc/init.d/presto status | grep -q 'Running as'
          failureThreshold: 1
          periodSeconds: 300
          timeoutSeconds: 10
        name: worker
        ports:
        - containerPort: 8080
      restartPolicy: Never
